//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursovayaEntities : DbContext
    {
        public KursovayaEntities()
            : base("name=KursovayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<calories> calories { get; set; }
        public DbSet<health_metrics> health_metrics { get; set; }
        public DbSet<nutrition> nutrition { get; set; }
        public DbSet<sleep> sleep { get; set; }
        public DbSet<user_conditions> user_conditions { get; set; }
        public DbSet<user_goals> user_goals { get; set; }
        public DbSet<user_habits> user_habits { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<water_intake> water_intake { get; set; }
        public DbSet<workouts> workouts { get; set; }
    }
}
