//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class nutrition
    {
        public int nutrition_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string product { get; set; }
        public Nullable<int> calories { get; set; }
        public Nullable<bool> calorie_counting { get; set; }
    
        public virtual users users { get; set; }
    }
}
