//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_habits
    {
        public int habit_id { get; set; }
        public string habit { get; set; }
        public string description { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
