//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.calories = new HashSet<calories>();
            this.health_metrics = new HashSet<health_metrics>();
            this.nutrition = new HashSet<nutrition>();
            this.sleep = new HashSet<sleep>();
            this.user_conditions = new HashSet<user_conditions>();
            this.user_goals = new HashSet<user_goals>();
            this.user_habits = new HashSet<user_habits>();
            this.water_intake = new HashSet<water_intake>();
            this.workouts = new HashSet<workouts>();
            this.habits = new HashSet<habits>();
            this.Goals = new HashSet<Goals>();
            this.UserProfileImages = new HashSet<UserProfileImages>();
        }
    
        public int user_id { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
        public string email { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public Nullable<bool> is_blocked { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string profile_image { get; set; }
    
        public virtual ICollection<calories> calories { get; set; }
        public virtual ICollection<health_metrics> health_metrics { get; set; }
        public virtual ICollection<nutrition> nutrition { get; set; }
        public virtual ICollection<sleep> sleep { get; set; }
        public virtual ICollection<user_conditions> user_conditions { get; set; }
        public virtual ICollection<user_goals> user_goals { get; set; }
        public virtual ICollection<user_habits> user_habits { get; set; }
        public virtual ICollection<water_intake> water_intake { get; set; }
        public virtual ICollection<workouts> workouts { get; set; }
        public virtual ICollection<habits> habits { get; set; }
        public virtual ICollection<Goals> Goals { get; set; }
        public virtual ICollection<UserProfileImages> UserProfileImages { get; set; }
    }
}
