//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileImages
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string image_path { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string profile_image { get; set; }
    
        public virtual users users { get; set; }
    }
}
