//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_goals
    {
        public int goal_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string goal_type { get; set; }
        public Nullable<decimal> target_weight { get; set; }
        public Nullable<System.DateTime> target_date { get; set; }
        public string description { get; set; }
    
        public virtual users users { get; set; }
    }
}
